version: "3.5"

networks:
    testing:
        driver: bridge

services:
    codebox:
        networks:
            - testing

    redis:
        networks:
            - testing

    codelab:
        networks:
            - testing
        ports:
            - "5000:5000"
        command:
            [
                "hypercorn",
                "--config=hypercorn.toml",
                "--reload",
                "--root-path=/api",
                "app.main:app"
            ]
        environment:
            - ENV=development
        volumes:
            - ./backend/app:/codelab/app
