version: "3.5"

services:

    redis:
        # configuration at /etc/redis/redis.conf  see https://github.com/dockerfile/redis/blob/master/Dockerfile
        image: 'redis:latest'
        volumes:
            - /tmp/data:/data
            - ./etc/redis:/etc/redis
        ports:
            - '6379:6379'
        container_name: redis

    codelab:
        build: .
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: codelab
        depends_on:
            - redis
        ports:
            - '5000:5000'
            - '5001:5001'
