version: "3.5"

networks:
    web:
        driver: bridge
    backend:
        driver: bridge
        internal: true

services:
    caddy:
        # see https://hub.docker.com/_/caddy
        container_name: caddy
        image: "caddy:alpine"
        init: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./frontend/dist:/dist
            - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
            - web
            - backend
        depends_on:
            - api

    redis:
        container_name: redis
        image: "redis:latest"
        init: true
        ports:
            - "6379:6379"
        networks:
            - backend

    api:
        container_name: codelab
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: codelab:latest
        init: true
        networks:
            - backend
        depends_on:
            - redis
            - codebox
        environment:
            - REDIS_URL=redis://redis:6379
            - CODEBOX_URL=http://codebox:8000
        volumes:
            - ./backend/app:/codelab/app

    codebox:
        image: codebox
        container_name: codebox
        build: https://github.com/andredias/codebox.git#main
        ports:
            - "8000:8000"
        networks:
            - backend
        init: true
        privileged: true
