version: "3.5"

networks:
    testing:
        driver: bridge

services:
    codebox:
        networks:
            - testing

    redis:
        networks:
            - testing

    api:
        networks:
            - testing
        ports:
            - "5000:5000"
        command:
            [
                "hypercorn",
                "--config=hypercorn.toml",
                "--reload",
                "app.main:create_app()"
            ]
        environment:
            - ENV=development
