[tool.poetry]
name = "codelab"
version = "0.1.0"
description = ""
authors = ["André Felipe Dias <andre.dias@pronus.io>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "*"
loguru = "*"
Hypercorn = "*"
uvloop = "*"
python-dotenv = "*"
aioredis = "*"
orjson = "*"
aiofiles = "*"
httpx = "*"
tenacity = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
asgi-lifespan = "*"
alt-pytest-asyncio = "*"
yapf = "*"
mypy = "*"
flake8 = "*"
isort = "*"
ipython = "*"
pdbpp = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 100
multi_line_output = 5
