[tool.poetry]
name = "codelab"
version = "0.1.0"
description = ""
authors = ["André Felipe Dias <andre.dias@pronus.io>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
loguru = "^0.5.3"
Hypercorn = "^0.11.2"
uvloop = "^0.14.0"
python-dotenv = "^0.15.0"
aioredis = "^1.3.1"
orjson = "^3.4.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
httpx = "^0.16.1"
asgi-lifespan = "^1.0.1"
alt-pytest-asyncio = "^0.5.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
