title = "Chaining Operators"
language = "Python"
sourcecode = """\
# Chaining Operators

x = 5
print(1 < x < 10)
print(10 < x < 20)
print(x < 10 < (x * 10) < 100)
print(10 > x <= 9)
print(5 == x > 4)
"""
