language = "Python"
title = "Reading from stdin - Example 1"
sourcecode = """\
\"\"\"
Reading from stdin Example 1
\"\"\"

import sys

for line in sys.stdin:
    print(f'line: {line!r}')  # repr(line)
"""
stdin = "7\n1\n3\n5 2 4 6 7\n"
