# https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148
# see section "Building your own Caddy-based image" at https://hub.docker.com/_/caddy

FROM caddy:2.3.0-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/digitalocean

FROM caddy:2.3.0

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
