title = "Array Indexes"
description = ""
id = "272bbc50a7bf8be588e12926541c05d1"
[[commands]]
command = "python array_indexes.py"
timeout = 0.1

[[responses]]
stdout = "[1, 3, 5]\n[5, 4, 3, 2, 1]\n"
stderr = ""
exit_code = 0

[sources]
"array_indexes.py" = "a = [1, 2, 3, 4, 5]\nprint(a[::2])  # iterate over the whole list in 2-increments\nprint(a[::-1])  # a useful idiom for 'x reversed'\n"
