title = "Array Indexes"
description = ""
id = "b7cef38b26a11b21e1e718ee2ab98510"
[[commands]]
command = "python main.py"
timeout = 0.1

[[responses]]
stdout = "[1, 3, 5]\n[5, 4, 3, 2, 1]\n"
stderr = ""
exit_code = 0

[sources]
"main.py" = """\
a = [1, 2, 3, 4, 5]
print(a[::2])  # iterate over the whole list in 2-increments
print(a[::-1])  # a useful idiom for 'x reversed'
"""
