stdout = "True\nFalse\nTrue\nTrue\nTrue\n"
stderr = ""
exit_code = 0
id = "45435b38e06635c0a2da8032a99dfed0"
title = "Chaining Operators"
description = ""
language = "python"
sourcecode = "x = 5\nprint(1 < x < 10)\nprint(10 < x < 20)\nprint(x < 10 < (x * 10) < 100)\nprint(10 > x <= 9)\nprint(5 == x > 4)\n"
