title = "Chaining Operators"
description = ""
id = "4605a6e1b09021ef3e8f4cae7a30bf4f"
[[commands]]
command = "python main.py"
timeout = 0.1

[[responses]]
stdout = "True\nFalse\nTrue\nTrue\nTrue\n"
stderr = ""
exit_code = 0

[sources]
"main.py" = """\
x = 5
print(1 < x < 10)
print(10 < x < 20)
print(x < 10 < (x * 10) < 100)
print(10 > x <= 9)
print(5 == x > 4)
"""
