title = "Decorators"
description = ""
id = "fec48e1900a290d2a9f3915bbcb0c4ee"
[[commands]]
command = "python main.py"
timeout = 0.1

[[responses]]
stdout = "Arguments: ('foo',) {}\nfoo\n"
stderr = ""
exit_code = 0

[sources]
"main.py" = """\
def print_args(function):
    def wrapper(*args, **kwargs):
        print('Arguments:', args, kwargs)
        return function(*args, **kwargs)
    return wrapper


@print_args
def write(text):
    print(text)


write('foo')
"""
