stdout = "Arguments: ('foo',) {}\nfoo\n"
stderr = ""
exit_code = 0
id = "a30defa15e67dce281338c360015a50e"
title = "Decorators"
description = ""
language = "python"
sourcecode = "def print_args(function):\n    def wrapper(*args, **kwargs):\n        print('Arguments:', args, kwargs)\n        return function(*args, **kwargs)\n    return wrapper\n\n\n@print_args\ndef write(text):\n    print(text)\n\n\nwrite('foo')\n"
