stdout = "1\n3\n5\n7\n9\n11\n13\n15\n17\n19\n"
stderr = ""
exit_code = 0
id = "566305950ceded9e2ecb1eef3b29118f"
title = "Generators"
description = ""
language = "python"
sourcecode = "odds = (n for n in range(1, 20) if n % 2)\nfor n in odds:\n    print(n)\n"
