title = ""
description = ""
id = "daed52a6d2aade4ddda9c536a840b595"
[[commands]]
type = "python"
command = "python generators.py"
timeout = 0.1

[[responses]]
stdout = "1\n3\n5\n7\n9\n11\n13\n15\n17\n19\n"
stderr = ""
exit_code = 0

[sources]
"generators.py" = """\
odds = (n for n in range(1, 20) if n % 2)
for n in odds:
    print(n)
"""
