title = "Hello World"
description = ""
id = "2a1e6e1aab91134494499768d8fcf136"
[[commands]]
command = "python hello_world.py"
timeout = 0.1

[[responses]]
stdout = "Hello, world!\n"
stderr = ""
exit_code = 0

[sources]
"hello_world.py" = "print(\"Hello, world!\")\n"
