stdout = "3 4\n3 4\n"
stderr = ""
exit_code = 0
id = "85b6d72ecd6d52ed5e134556e7f8a643"
title = "Unpacking Arguments"
description = ""
language = "python"
sourcecode = "def draw_point(x, y):\n    print(x, y)\n\n\npoint_foo = (3, 4)\npoint_bar = {'y': 4, 'x': 3}\ndraw_point(*point_foo)\ndraw_point(**point_bar)\n"
