title = "Unpacking Arguments"
description = ""
id = "63a90fb000c36f867dfe96459a986318"
[[commands]]
command = "python arguments_unpacking.py"
timeout = 0.1

[[responses]]
stdout = "3 4\n2 3\n"
stderr = ""
exit_code = 0

[sources]
"arguments_unpacking.py" = "def draw_point(x, y):\n    print(x, y)\n\n\npoint_foo = (3, 4)\npoint_bar = {'y': 3, 'x': 2}\ndraw_point(*point_foo)\ndraw_point(**point_bar)\n"
