title = "Unpacking Arguments"
language = "python"
sourcecode = """\
# Unpacking Arguments


def draw_point(x, y):
    print(x, y)


point_foo = (3, 4)
point_bar = {'y': 4, 'x': 3}
draw_point(*point_foo)
draw_point(**point_bar)
"""
