title = "Unpacking Arguments"
language = "Python"
sourcecode = """\
# Unpacking Arguments


def draw_point(x: int, y: int) -> None:
    print(x, y)


point_foo = (3, 4)
point_bar = {'y': 4, 'x': 3}
draw_point(*point_foo)
draw_point(**point_bar)
"""
